---
abstract: 'MurmurHash3 Implementation For Perl'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Digest::MurmurHash3
name: Digest-MurmurHash3
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.02
version: 0.02
